name: subreporte-eph
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas=2.2.2
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scikit-learn=1.4.2
  - scipy=1.13.1
  - xgboost=2.1.4
  - imbalanced-learn=0.12.3
  - pip
  - pip:
      - some-pip-only-packages-if-needed
